import type { ScheduledClass } from './types'

export const MOCK_SCHEDULED_CLASSES: ScheduledClass[] = [
  {
    id: 'sch-101',
    title: 'Python Basics & Syntax Overview',
    courseClass: 'BCA - 3rd Semester',
    semester: '3rd Semester',
    module: 'Module 1',
    date: '2026-10-08', // Today
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    duration: '1 hour',
    type: 'in-person',
    room: 'Room 302',
    description: 'Introduction to Python variable types, control statements, and live coding exercises.',
    attachedMaterialTitles: ['Python Object-Oriented Concepts Cheat Sheet'],
    capacity: 35,
    attendanceRequired: true,
    allowRecording: false,
    notifyStudents: true,
    status: 'ongoing',
  },
  {
    id: 'sch-102',
    title: 'Web Development & React Hooks Lab',
    courseClass: 'BCA - 5th Semester',
    semester: '5th Semester',
    module: 'Module 4',
    date: '2026-10-08', // Today
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    duration: '1.5 hours',
    type: 'online',
    meetingPlatform: 'Google Meet',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    description: 'Practical lab session building custom React hooks for form validation and state sync.',
    attachedMaterialTitles: [
      'React Hooks & Custom Hooks Notes',
      'Introduction to React Hooks & State Management',
    ],
    capacity: 30,
    attendanceRequired: true,
    allowRecording: true,
    notifyStudents: true,
    status: 'scheduled',
  },
  {
    id: 'sch-103',
    title: 'Capstone Project Discussion & Architecture Review',
    courseClass: 'BCA - 5th Semester',
    semester: '5th Semester',
    module: 'Module 4',
    date: '2026-10-08', // Today
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    duration: '1.5 hours',
    type: 'in-person',
    room: 'Lab 1',
    description: 'One-on-one team evaluation of database schema design and frontend API integration.',
    capacity: 25,
    attendanceRequired: true,
    allowRecording: false,
    notifyStudents: true,
    status: 'scheduled',
  },
  {
    id: 'sch-104',
    title: 'Database Management Systems & Indexing',
    courseClass: 'BCA - 4th Semester',
    semester: '4th Semester',
    module: 'Module 2',
    date: '2026-10-09', // Tomorrow
    startTime: '10:00 AM',
    endTime: '11:30 AM',
    duration: '1.5 hours',
    type: 'in-person',
    room: 'Hall A',
    description: 'PostgreSQL indexing algorithms, execution plan analysis, and B-tree optimization.',
    attachedMaterialTitles: ['Database Indexing & Query Optimization Handbook'],
    capacity: 40,
    attendanceRequired: true,
    allowRecording: true,
    notifyStudents: true,
    status: 'scheduled',
  },
  {
    id: 'sch-105',
    title: 'SQL Joins & Subqueries Masterclass',
    courseClass: 'BCA - 4th Semester',
    semester: '4th Semester',
    module: 'Module 2',
    date: '2026-10-06', // Past
    startTime: '09:30 AM',
    endTime: '11:00 AM',
    duration: '1.5 hours',
    type: 'online',
    meetingPlatform: 'Zoom',
    meetingLink: 'https://zoom.us/j/123456789',
    description: 'Detailed lecture on relational algebra, inner/outer joins, and nested subqueries.',
    attachedMaterialTitles: ['SQL Joins & Subqueries Masterclass'],
    capacity: 35,
    attendanceRequired: true,
    allowRecording: true,
    notifyStudents: true,
    status: 'completed',
  },
  {
    id: 'sch-106',
    title: 'Advanced Python Decorators & Generators',
    courseClass: 'BCA - 3rd Semester',
    semester: '3rd Semester',
    module: 'Module 3',
    date: '2026-10-07', // Yesterday
    startTime: '01:00 PM',
    endTime: '02:30 PM',
    duration: '1.5 hours',
    type: 'in-person',
    room: 'Room 205',
    description: 'Lecture cancelled due to departmental faculty conference.',
    capacity: 30,
    attendanceRequired: false,
    allowRecording: false,
    notifyStudents: true,
    status: 'cancelled',
  },
]

export const AVAILABLE_ROOMS = ['Room 101', 'Room 205', 'Room 302', 'Lab 1', 'Lab 3', 'Hall A', 'Hall B']

export const AVAILABLE_COURSES = ['BCA - 3rd Semester', 'BCA - 4th Semester', 'BCA - 5th Semester']

export const AVAILABLE_MODULES = ['Module 1', 'Module 2', 'Module 3', 'Module 4']
