import type { LearningMaterial } from './types'

export const MOCK_LEARNING_MATERIALS: LearningMaterial[] = [
  {
    id: 'mat-1',
    title: 'React Hooks & Custom Hooks Notes',
    description: 'Complete notes covering useState, useEffect, useContext, and building custom hooks with real-world examples.',
    type: 'pdf',
    courseClass: 'BCA - 5th Semester',
    semester: '5th Semester',
    module: 'Module 4',
    topic: 'React State & Hooks',
    status: 'published',
    uploadedDate: 'Oct 8, 2026',
    uploadedBy: 'Prof. Alex Morgan',
    fileName: 'react-hooks-master-notes.pdf',
    fileSize: '2.4 MB',
    fileUrl: '#',
  },
  {
    id: 'mat-2',
    title: 'Introduction to React Hooks & State Management',
    description: 'Comprehensive video class explaining functional components, state lifecycle, and hook dependencies.',
    type: 'video',
    courseClass: 'BCA - 5th Semester',
    semester: '5th Semester',
    module: 'Module 4',
    topic: 'React State & Hooks',
    status: 'published',
    uploadedDate: 'Oct 7, 2026',
    uploadedBy: 'Prof. Alex Morgan',
    videoSource: 'url',
    videoUrl: 'https://www.youtube.com/watch?v=dpw9EHDh2bM',
    duration: '42 min',
  },
  {
    id: 'mat-3',
    title: 'Database Indexing & Query Optimization Handbook',
    description: 'Guide to B-Tree indexes, execution plans, join algorithms, and query performance tuning in PostgreSQL.',
    type: 'pdf',
    courseClass: 'BCA - 4th Semester',
    semester: '4th Semester',
    module: 'Module 2',
    topic: 'Database Performance',
    status: 'published',
    uploadedDate: 'Oct 5, 2026',
    uploadedBy: 'Prof. Alex Morgan',
    fileName: 'db-indexing-guide.pdf',
    fileSize: '4.1 MB',
    fileUrl: '#',
  },
  {
    id: 'mat-4',
    title: 'SQL Joins & Subqueries Masterclass',
    description: 'Recorded lecture covering Inner, Left, Right, Full Outer Joins, and Correlated Subqueries.',
    type: 'video',
    courseClass: 'BCA - 4th Semester',
    semester: '4th Semester',
    module: 'Module 2',
    topic: 'Relational Queries',
    status: 'published',
    uploadedDate: 'Oct 4, 2026',
    uploadedBy: 'Prof. Alex Morgan',
    videoSource: 'upload',
    fileName: 'sql-joins-masterclass.mp4',
    fileSize: '128 MB',
    duration: '58 min',
  },
  {
    id: 'mat-5',
    title: 'Python Object-Oriented Concepts Cheat Sheet',
    description: 'Quick reference sheet for Classes, Inheritance, Polymorphism, Encapsulation, and Magic Methods.',
    type: 'pdf',
    courseClass: 'BCA - 3rd Semester',
    semester: '3rd Semester',
    module: 'Module 1',
    topic: 'OOP Fundamentals',
    status: 'draft',
    uploadedDate: 'Oct 2, 2026',
    uploadedBy: 'Prof. Alex Morgan',
    fileName: 'python-oop-cheatsheet.pdf',
    fileSize: '1.8 MB',
    fileUrl: '#',
  },
  {
    id: 'mat-6',
    title: 'Python Decorators & Generators Walkthrough',
    description: 'In-depth video session demonstrating function decorators, closures, and generator functions.',
    type: 'video',
    courseClass: 'BCA - 3rd Semester',
    semester: '3rd Semester',
    module: 'Module 3',
    topic: 'Advanced Python',
    status: 'draft',
    uploadedDate: 'Sep 28, 2026',
    uploadedBy: 'Prof. Alex Morgan',
    videoSource: 'url',
    videoUrl: 'https://www.youtube.com/watch?v=r7DZu7A-F-g',
    duration: '35 min',
  },
]
