export * as schedule from './schedule'
export * as materials from './materials'
export * as mentorDashboard from './dashboard'
export * as myStudents from './my-students'
export * as batchOverview from './batch-overview'
export * as studentSubmissionsCodeReviews from './student-submissions-code-reviews'
export * as capstoneProjects from './capstone-projects'
export * as attendanceTracking from './attendance-tracking'
export * as schedule1On1Sessions from './schedule-1-on-1-sessions'
export * as performanceReports from './performance-reports'
export * as helpdeskResourceHub from './helpdesk-resource-hub'
export * as assignments from './assignments'
export * as exams from './exams'
export * as myClasses from './my-classes'
export * as results from './results'
export * as timetable from './timetable'
export * as messages from './messages'
export * as notifications from './notifications'
export * as profile from './profile'
export * as settings from './settings'

export { SchedulePage } from './schedule'
export { MaterialsPage } from './materials'
export { MentorDashboardPage } from './dashboard'
export { MyStudentsPage } from './my-students'
export { BatchOverviewPage } from './batch-overview'
export { StudentSubmissionsCodeReviewsPage } from './student-submissions-code-reviews'
export { CapstoneProjectsPage } from './capstone-projects'
export { AttendanceTrackingPage } from './attendance-tracking'
export { Schedule1On1SessionsPage } from './schedule-1-on-1-sessions'
export { PerformanceReportsPage } from './performance-reports'
export { HelpdeskResourceHubPage } from './helpdesk-resource-hub'
export { AssignmentsPage, CreateAssignmentPage } from './assignments'
export { ExamsPage, ExamDetailsPage } from './exams'
export { MyClassesPage, ClassDetailsPage } from './my-classes'
export { ResultsPage, ResultDetailsPage } from './results'
export { TimetablePage } from './timetable'
export { MessagesPage } from './messages'
export { NotificationsPage } from './notifications'
export { ProfilePage } from './profile'
export { SettingsPage } from './settings'
