import type { AssignedStudent } from '../types'

export const MOCK_ASSIGNED_STUDENTS: AssignedStudent[] = [
  {
    id: 's-1',
    mentorId: 'user-mentor',
    name: 'Muhammad Riyan',
    rollNumber: 'BCA23001',
    avatarInitials: 'MR',
    classBatch: 'BCA - 3rd Year',
    email: 'muhammad.riyan@example.com',
    phone: '+91 98765 43210',
    attendancePercentage: 92,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'late' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.8',
      assignmentsCompleted: 14,
      totalAssignments: 15,
      capstoneProject: 'AI Powered LMS Analytics Engine',
    },
  },
  {
    id: 's-2',
    mentorId: 'user-mentor',
    name: 'Fathima Nida',
    rollNumber: 'BCA23002',
    avatarInitials: 'FN',
    classBatch: 'BCA - 3rd Year',
    email: 'fathima.nida@example.com',
    phone: '+91 98765 43211',
    attendancePercentage: 88,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'late' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.6',
      assignmentsCompleted: 13,
      totalAssignments: 15,
      capstoneProject: 'E-Commerce Microservices Platform',
    },
  },
  {
    id: 's-3',
    mentorId: 'user-mentor',
    name: 'Alan Shihab',
    rollNumber: 'BCA23003',
    avatarInitials: 'AS',
    classBatch: 'BCA - 3rd Year',
    email: 'alan.shihab@example.com',
    phone: '+91 98765 43212',
    attendancePercentage: 76,
    statusToday: 'late',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'late' },
      { date: '03 Oct 2026', status: 'absent' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.1',
      assignmentsCompleted: 10,
      totalAssignments: 15,
      capstoneProject: 'Smart IoT Home Automation Tracker',
    },
  },
  {
    id: 's-4',
    mentorId: 'user-mentor',
    name: 'Rinsha K',
    rollNumber: 'BCA23004',
    avatarInitials: 'RK',
    classBatch: 'BCA - 3rd Year',
    email: 'rinsha.k@example.com',
    phone: '+91 98765 43213',
    attendancePercentage: 95,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.9',
      assignmentsCompleted: 15,
      totalAssignments: 15,
      capstoneProject: 'Healthcare Tele-consultation App',
    },
  },
  {
    id: 's-5',
    mentorId: 'user-mentor',
    name: 'Aiswarya Lakshmi',
    rollNumber: 'BCA23005',
    avatarInitials: 'AL',
    classBatch: 'BCA - 4th Semester',
    email: 'aiswarya.l@example.com',
    phone: '+91 98765 43214',
    attendancePercentage: 90,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'late' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.7',
      assignmentsCompleted: 12,
      totalAssignments: 14,
      capstoneProject: 'Cloud Resource Optimization Dashboard',
    },
  },
  {
    id: 's-6',
    mentorId: 'user-mentor',
    name: 'Devadathan P',
    rollNumber: 'BCA23006',
    avatarInitials: 'DP',
    classBatch: 'BCA - 4th Semester',
    email: 'devadathan.p@example.com',
    phone: '+91 98765 43215',
    attendancePercentage: 64,
    statusToday: 'absent',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'absent' },
      { date: '03 Oct 2026', status: 'absent' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'absent' },
    ],
    academicSummary: {
      gpa: '2.8',
      assignmentsCompleted: 8,
      totalAssignments: 14,
      capstoneProject: 'Automated Code Review Assistant',
    },
  },
  {
    id: 's-7',
    mentorId: 'user-mentor',
    name: 'Farhan Ahamed',
    rollNumber: 'BCA23007',
    avatarInitials: 'FA',
    classBatch: 'BCA - 4th Semester',
    email: 'farhan.ahamed@example.com',
    phone: '+91 98765 43216',
    attendancePercentage: 91,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.65',
      assignmentsCompleted: 13,
      totalAssignments: 14,
      capstoneProject: 'Fintech Expense Analyzer & Budgeter',
    },
  },
  {
    id: 's-8',
    mentorId: 'user-mentor',
    name: 'Gouri Parvathy',
    rollNumber: 'BCA23008',
    avatarInitials: 'GP',
    classBatch: 'BCA - 4th Semester',
    email: 'gouri.parvathy@example.com',
    phone: '+91 98765 43217',
    attendancePercentage: 94,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.85',
      assignmentsCompleted: 14,
      totalAssignments: 14,
      capstoneProject: 'Real-time Collaborative Whiteboard',
    },
  },
  {
    id: 's-9',
    mentorId: 'user-mentor',
    name: 'Hisham Moosa',
    rollNumber: 'BCA23009',
    avatarInitials: 'HM',
    classBatch: 'BCA - 2nd Year',
    email: 'hisham.moosa@example.com',
    phone: '+91 98765 43218',
    attendancePercentage: 58,
    statusToday: 'absent',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'absent' },
      { date: '03 Oct 2026', status: 'late' },
      { date: '02 Oct 2026', status: 'absent' },
      { date: '01 Oct 2026', status: 'absent' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '2.5',
      assignmentsCompleted: 6,
      totalAssignments: 12,
      capstoneProject: 'Campus Event Management Portal',
    },
  },
  {
    id: 's-10',
    mentorId: 'user-mentor',
    name: 'Kavya Suresh',
    rollNumber: 'BCA23010',
    avatarInitials: 'KS',
    classBatch: 'BCA - 2nd Year',
    email: 'kavya.suresh@example.com',
    phone: '+91 98765 43219',
    attendancePercentage: 89,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'late' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.5',
      assignmentsCompleted: 11,
      totalAssignments: 12,
      capstoneProject: 'Library Management System',
    },
  },
  {
    id: 's-11',
    mentorId: 'user-mentor',
    name: 'Nikhil Raj',
    rollNumber: 'BCA23011',
    avatarInitials: 'NR',
    classBatch: 'BCA - 2nd Year',
    email: 'nikhil.raj@example.com',
    phone: '+91 98765 43220',
    attendancePercentage: 93,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.75',
      assignmentsCompleted: 12,
      totalAssignments: 12,
      capstoneProject: 'Student Attendance PWA App',
    },
  },
  {
    id: 's-12',
    mentorId: 'user-mentor',
    name: 'Saniya Thomas',
    rollNumber: 'BCA23012',
    avatarInitials: 'ST',
    classBatch: 'BCA - 2nd Year',
    email: 'saniya.thomas@example.com',
    phone: '+91 98765 43221',
    attendancePercentage: 62,
    statusToday: 'absent',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'absent' },
      { date: '03 Oct 2026', status: 'absent' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'absent' },
    ],
    academicSummary: {
      gpa: '2.7',
      assignmentsCompleted: 7,
      totalAssignments: 12,
      capstoneProject: 'Online Assessment Engine',
    },
  },
  {
    id: 's-13',
    mentorId: 'user-mentor',
    name: 'Adithyan V',
    rollNumber: 'BCA23013',
    avatarInitials: 'AV',
    classBatch: 'BCA - 3rd Year',
    email: 'adithyan.v@example.com',
    phone: '+91 98765 43222',
    attendancePercentage: 86,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'late' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.4',
      assignmentsCompleted: 13,
      totalAssignments: 15,
      capstoneProject: 'Placement Drive Notification Bot',
    },
  },
  {
    id: 's-14',
    mentorId: 'user-mentor',
    name: 'Bhavana Nair',
    rollNumber: 'BCA23014',
    avatarInitials: 'BN',
    classBatch: 'BCA - 3rd Year',
    email: 'bhavana.nair@example.com',
    phone: '+91 98765 43223',
    attendancePercentage: 97,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.95',
      assignmentsCompleted: 15,
      totalAssignments: 15,
      capstoneProject: 'Algorithmic Trading Dashboard',
    },
  },
  {
    id: 's-15',
    mentorId: 'user-mentor',
    name: 'Cyril Joseph',
    rollNumber: 'BCA23015',
    avatarInitials: 'CJ',
    classBatch: 'BCA - 3rd Year',
    email: 'cyril.joseph@example.com',
    phone: '+91 98765 43224',
    attendancePercentage: 78,
    statusToday: 'late',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'late' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'late' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.2',
      assignmentsCompleted: 11,
      totalAssignments: 15,
      capstoneProject: 'Virtual Reality Campus Tour',
    },
  },
  {
    id: 's-16',
    mentorId: 'user-mentor',
    name: 'Diya Krishnan',
    rollNumber: 'BCA23016',
    avatarInitials: 'DK',
    classBatch: 'BCA - 4th Semester',
    email: 'diya.krishnan@example.com',
    phone: '+91 98765 43225',
    attendancePercentage: 92,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'late' },
    ],
    academicSummary: {
      gpa: '3.8',
      assignmentsCompleted: 13,
      totalAssignments: 14,
      capstoneProject: 'Automated Quiz & Flashcard Generator',
    },
  },
  {
    id: 's-17',
    mentorId: 'user-mentor',
    name: 'Eldho Paul',
    rollNumber: 'BCA23017',
    avatarInitials: 'EP',
    classBatch: 'BCA - 4th Semester',
    email: 'eldho.paul@example.com',
    phone: '+91 98765 43226',
    attendancePercentage: 71,
    statusToday: 'late',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'late' },
      { date: '03 Oct 2026', status: 'absent' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'late' },
    ],
    academicSummary: {
      gpa: '2.9',
      assignmentsCompleted: 9,
      totalAssignments: 14,
      capstoneProject: 'Peer-to-Peer Code Mentorship Platform',
    },
  },
  {
    id: 's-18',
    mentorId: 'user-mentor',
    name: 'Haripriya M',
    rollNumber: 'BCA23018',
    avatarInitials: 'HM',
    classBatch: 'BCA - 4th Semester',
    email: 'haripriya.m@example.com',
    phone: '+91 98765 43227',
    attendancePercentage: 96,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.9',
      assignmentsCompleted: 14,
      totalAssignments: 14,
      capstoneProject: 'Intelligent Schedule Optimizer',
    },
  },
  {
    id: 's-19',
    mentorId: 'user-mentor',
    name: 'Ishaan Verma',
    rollNumber: 'BCA23019',
    avatarInitials: 'IV',
    classBatch: 'BCA - 2nd Year',
    email: 'ishaan.verma@example.com',
    phone: '+91 98765 43228',
    attendancePercentage: 84,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'late' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.3',
      assignmentsCompleted: 10,
      totalAssignments: 12,
      capstoneProject: 'Student Portfolio Generator',
    },
  },
  {
    id: 's-20',
    mentorId: 'user-mentor',
    name: 'Jiya Rose',
    rollNumber: 'BCA23020',
    avatarInitials: 'JR',
    classBatch: 'BCA - 2nd Year',
    email: 'jiya.rose@example.com',
    phone: '+91 98765 43229',
    attendancePercentage: 91,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.6',
      assignmentsCompleted: 11,
      totalAssignments: 12,
      capstoneProject: 'Interactive Data Structures Visualizer',
    },
  },
  {
    id: 's-21',
    mentorId: 'user-mentor',
    name: 'Karthik S',
    rollNumber: 'BCA23021',
    avatarInitials: 'KS',
    classBatch: 'BCA - 2nd Year',
    email: 'karthik.s@example.com',
    phone: '+91 98765 43230',
    attendancePercentage: 80,
    statusToday: 'late',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'late' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'late' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.2',
      assignmentsCompleted: 9,
      totalAssignments: 12,
      capstoneProject: 'Sub-domain DNS Health Monitor',
    },
  },
  {
    id: 's-22',
    mentorId: 'user-mentor',
    name: 'Lakshmi Menon',
    rollNumber: 'BCA23022',
    avatarInitials: 'LM',
    classBatch: 'BCA - 3rd Year',
    email: 'lakshmi.menon@example.com',
    phone: '+91 98765 43231',
    attendancePercentage: 94,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.85',
      assignmentsCompleted: 15,
      totalAssignments: 15,
      capstoneProject: 'Micro-learning Gamified Portal',
    },
  },
  {
    id: 's-23',
    mentorId: 'user-mentor',
    name: 'Manoj Kumar',
    rollNumber: 'BCA23023',
    avatarInitials: 'MK',
    classBatch: 'BCA - 4th Semester',
    email: 'manoj.kumar@example.com',
    phone: '+91 98765 43232',
    attendancePercentage: 73,
    statusToday: 'late',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'late' },
      { date: '03 Oct 2026', status: 'late' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'absent' },
      { date: '30 Sep 2026', status: 'present' },
    ],
    academicSummary: {
      gpa: '3.0',
      assignmentsCompleted: 9,
      totalAssignments: 14,
      capstoneProject: 'Real-time Chat & Video Call Engine',
    },
  },
  {
    id: 's-24',
    mentorId: 'user-mentor',
    name: 'Nivedita R',
    rollNumber: 'BCA23024',
    avatarInitials: 'NR',
    classBatch: 'BCA - 2nd Year',
    email: 'nivedita.r@example.com',
    phone: '+91 98765 43233',
    attendancePercentage: 91,
    statusToday: 'present',
    assignedMentorName: 'Prof. Sarah Jenkins',
    recentAttendance: [
      { date: '04 Oct 2026', status: 'present' },
      { date: '03 Oct 2026', status: 'present' },
      { date: '02 Oct 2026', status: 'present' },
      { date: '01 Oct 2026', status: 'present' },
      { date: '30 Sep 2026', status: 'late' },
    ],
    academicSummary: {
      gpa: '3.7',
      assignmentsCompleted: 11,
      totalAssignments: 12,
      capstoneProject: 'AI Document Summarizer for Students',
    },
  },
]
