import type { MentorExam } from './types'

export const MOCK_MENTOR_EXAMS: MentorExam[] = [
  {
    id: 'exam-101',
    title: 'Flutter Development',
    classBatch: 'Final Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Mobile App Development',
    year: 'Final Year',
    date: '2026-10-07',
    formattedDate: '07 Oct',
    time: '02:00 PM',
    duration: '3 Hours',
    studentsCount: 22,
    room: 'Lab 4',
    status: 'ongoing',
    totalMarks: 100,
    passingMarks: 40,
    instructions: 'Bring your laptop with Flutter SDK 3.x and Android Studio configured. Submission via GitHub classroom repository.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-1', name: 'Aarav Sharma', rollNumber: 'BCA-2023-001', email: 'aarav.s@example.com', marksObtained: null, totalMarks: 100, status: 'pending' },
      { id: 'st-2', name: 'Priya Patel', rollNumber: 'BCA-2023-002', email: 'priya.p@example.com', marksObtained: null, totalMarks: 100, status: 'pending' },
      { id: 'st-3', name: 'Rohan Gupta', rollNumber: 'BCA-2023-003', email: 'rohan.g@example.com', marksObtained: null, totalMarks: 100, status: 'pending' },
    ],
  },
  {
    id: 'exam-102',
    title: 'Python Programming Basics',
    classBatch: 'BCA - 1st Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Computer Science',
    year: '1st Year',
    date: '2026-10-07',
    formattedDate: '07 Oct',
    time: '10:00 AM',
    duration: '2 Hours',
    studentsCount: 30,
    room: 'Room 101',
    status: 'ongoing',
    totalMarks: 50,
    passingMarks: 20,
    instructions: 'Written theory & short coding exercise on lists, dictionaries, functions, and file I/O.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-4', name: 'Sneha Rao', rollNumber: 'BCA-2025-004', email: 'sneha.r@example.com', marksObtained: null, totalMarks: 50, status: 'pending' },
      { id: 'st-5', name: 'Vikram Singh', rollNumber: 'BCA-2025-005', email: 'vikram.s@example.com', marksObtained: null, totalMarks: 50, status: 'pending' },
    ],
  },
  {
    id: 'exam-103',
    title: 'Web Technologies',
    classBatch: 'BCA - 2nd Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Web Technologies',
    year: '2nd Year',
    date: '2026-10-08',
    formattedDate: '08 Oct',
    time: '11:00 AM',
    duration: '2 Hours',
    studentsCount: 28,
    room: 'Room 201',
    status: 'upcoming',
    totalMarks: 75,
    passingMarks: 30,
    instructions: 'Covers HTML5 semantic layout, CSS Flexbox/Grid, JavaScript DOM manipulation and async/await API calls.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-6', name: 'Ananya Verma', rollNumber: 'BCA-2024-012', email: 'ananya.v@example.com', marksObtained: null, totalMarks: 75, status: 'pending' },
      { id: 'st-7', name: 'Devansh Reddy', rollNumber: 'BCA-2024-015', email: 'devansh.r@example.com', marksObtained: null, totalMarks: 75, status: 'pending' },
    ],
  },
  {
    id: 'exam-104',
    title: 'Data Structures & Algorithms Mid-Term',
    classBatch: 'BCA - 1st Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Core Programming',
    year: '1st Year',
    date: '2026-10-12',
    formattedDate: '12 Oct',
    time: '09:30 AM',
    duration: '3 Hours',
    studentsCount: 32,
    room: 'Hall A',
    status: 'upcoming',
    totalMarks: 100,
    passingMarks: 40,
    instructions: 'Comprehensive exam on arrays, linked lists, stacks, queues, trees, and time complexity analysis.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-8', name: 'Kavya Nair', rollNumber: 'BCA-2025-018', email: 'kavya.n@example.com', marksObtained: null, totalMarks: 100, status: 'pending' },
    ],
  },
  {
    id: 'exam-105',
    title: 'Database Management Systems Assessment',
    classBatch: 'BCA - 2nd Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Database Systems',
    year: '2nd Year',
    date: '2026-10-05',
    formattedDate: '05 Oct',
    time: '01:30 PM',
    duration: '2 Hours',
    studentsCount: 32,
    room: 'Room 205',
    status: 'results_pending',
    totalMarks: 50,
    passingMarks: 20,
    instructions: 'SQL queries, normalization (1NF-3NF), ER diagrams and transaction isolation levels.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-9', name: 'Manish Kumar', rollNumber: 'BCA-2024-022', email: 'manish.k@example.com', marksObtained: 44, totalMarks: 50, grade: 'A', status: 'graded' },
      { id: 'st-10', name: 'Ishita Joshi', rollNumber: 'BCA-2024-025', email: 'ishita.j@example.com', marksObtained: null, totalMarks: 50, status: 'pending' },
    ],
  },
  {
    id: 'exam-106',
    title: 'Computer Networks & Security Viva',
    classBatch: 'BCA - 3rd Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Networking & Cybersecurity',
    year: '3rd Year',
    date: '2026-10-04',
    formattedDate: '04 Oct',
    time: '10:00 AM',
    duration: '1.5 Hours',
    studentsCount: 26,
    room: 'Lab 1',
    status: 'results_pending',
    totalMarks: 50,
    passingMarks: 20,
    instructions: 'Individual oral viva and socket programming demonstration.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-11', name: 'Siddharth Iyer', rollNumber: 'BCA-2023-040', email: 'siddharth.i@example.com', marksObtained: 48, totalMarks: 50, grade: 'A+', status: 'graded' },
      { id: 'st-12', name: 'Meera Deshmukh', rollNumber: 'BCA-2023-048', email: 'meera.d@example.com', marksObtained: null, totalMarks: 50, status: 'pending' },
    ],
  },
  {
    id: 'exam-107',
    title: 'Object Oriented Programming with Java',
    classBatch: 'BCA - 1st Year',
    courseName: 'Bachelor of Computer Applications',
    subject: 'Java Programming',
    year: '1st Year',
    date: '2026-09-28',
    formattedDate: '28 Sep',
    time: '09:00 AM',
    duration: '2.5 Hours',
    studentsCount: 34,
    room: 'Room 108',
    status: 'completed',
    totalMarks: 100,
    passingMarks: 40,
    instructions: 'Final practical evaluation on OOP concepts, inheritance, interfaces, and Java Swing UI.',
    mentorId: 'user-mentor',
    studentGrades: [
      { id: 'st-13', name: 'Rahul Mehta', rollNumber: 'BCA-2025-030', email: 'rahul.m@example.com', marksObtained: 88, totalMarks: 100, grade: 'A', status: 'graded' },
      { id: 'st-14', name: 'Diya Choudhury', rollNumber: 'BCA-2025-033', email: 'diya.c@example.com', marksObtained: 92, totalMarks: 100, grade: 'A+', status: 'graded' },
    ],
  },
]
