import type { MentorClass } from './types'

export const MOCK_MENTOR_CLASSES: MentorClass[] = [
  {
    id: 'cls-101',
    title: 'Data Structures & Algorithms',
    courseCode: 'BCA-103',
    courseName: 'Bachelor of Computer Applications',
    program: 'BCA',
    year: '1st Year',
    semester: 'Semester 1',
    studentsCount: 30,
    room: 'Room 101',
    status: 'completed',
    iconType: 'algo',
    mentorId: 'user-mentor',
    schedule: 'Mon, Wed, Fri · 09:00 AM - 10:30 AM',
    description: 'Comprehensive study of linear and non-linear data structures, space & time complexity, sorting and searching algorithms.',
    attendanceRate: 94,
    syllabusProgress: 100,
    enrolledStudents: [
      { id: 'st-1', name: 'Aarav Sharma', rollNumber: 'BCA-2025-001', email: 'aarav.sharma@example.com', attendancePercentage: 96, statusToday: 'present' },
      { id: 'st-2', name: 'Priya Patel', rollNumber: 'BCA-2025-002', email: 'priya.patel@example.com', attendancePercentage: 92, statusToday: 'present' },
      { id: 'st-3', name: 'Rohan Gupta', rollNumber: 'BCA-2025-003', email: 'rohan.gupta@example.com', attendancePercentage: 88, statusToday: 'absent' },
      { id: 'st-4', name: 'Sneha Rao', rollNumber: 'BCA-2025-004', email: 'sneha.rao@example.com', attendancePercentage: 98, statusToday: 'present' },
      { id: 'st-5', name: 'Vikram Singh', rollNumber: 'BCA-2025-005', email: 'vikram.singh@example.com', attendancePercentage: 90, statusToday: 'late' },
    ],
  },
  {
    id: 'cls-102',
    title: 'Web Development Fundamentals',
    courseCode: 'BCA-201',
    courseName: 'Bachelor of Computer Applications',
    program: 'BCA',
    year: '2nd Year',
    semester: 'Semester 3',
    studentsCount: 28,
    room: 'Lab 3',
    status: 'active',
    iconType: 'web',
    mentorId: 'user-mentor',
    schedule: 'Tue, Thu · 11:00 AM - 01:00 PM',
    description: 'Modern front-end engineering with HTML5, CSS3, JavaScript (ES6+), React.js, and responsive user interfaces.',
    attendanceRate: 91,
    syllabusProgress: 68,
    enrolledStudents: [
      { id: 'st-6', name: 'Ananya Verma', rollNumber: 'BCA-2024-012', email: 'ananya.v@example.com', attendancePercentage: 95, statusToday: 'present' },
      { id: 'st-7', name: 'Devansh Reddy', rollNumber: 'BCA-2024-015', email: 'devansh.r@example.com', attendancePercentage: 89, statusToday: 'present' },
      { id: 'st-8', name: 'Kavya Nair', rollNumber: 'BCA-2024-018', email: 'kavya.n@example.com', attendancePercentage: 93, statusToday: 'present' },
    ],
  },
  {
    id: 'cls-103',
    title: 'Database Management Systems',
    courseCode: 'BCA-204',
    courseName: 'Bachelor of Computer Applications',
    program: 'BCA',
    year: '2nd Year',
    semester: 'Semester 3',
    studentsCount: 32,
    room: 'Room 205',
    status: 'active',
    iconType: 'database',
    mentorId: 'user-mentor',
    schedule: 'Mon, Wed · 02:00 PM - 03:30 PM',
    description: 'Relational database concepts, SQL querying, normalization, indexing, transaction management, and PostgreSQL.',
    attendanceRate: 88,
    syllabusProgress: 60,
    enrolledStudents: [
      { id: 'st-9', name: 'Manish Kumar', rollNumber: 'BCA-2024-022', email: 'manish.k@example.com', attendancePercentage: 85, statusToday: 'present' },
      { id: 'st-10', name: 'Ishita Joshi', rollNumber: 'BCA-2024-025', email: 'ishita.j@example.com', attendancePercentage: 91, statusToday: 'present' },
    ],
  },
  {
    id: 'cls-104',
    title: 'Object Oriented Programming in Java',
    courseCode: 'BCA-105',
    courseName: 'Bachelor of Computer Applications',
    program: 'BCA',
    year: '1st Year',
    semester: 'Semester 2',
    studentsCount: 34,
    room: 'Room 108',
    status: 'active',
    iconType: 'code',
    mentorId: 'user-mentor',
    schedule: 'Tue, Fri · 09:30 AM - 11:00 AM',
    description: 'Principles of OOP: Encapsulation, Inheritance, Polymorphism, Abstraction, Exception Handling, and Java Collections.',
    attendanceRate: 92,
    syllabusProgress: 45,
    enrolledStudents: [
      { id: 'st-11', name: 'Rahul Mehta', rollNumber: 'BCA-2025-030', email: 'rahul.m@example.com', attendancePercentage: 94, statusToday: 'present' },
      { id: 'st-12', name: 'Diya Choudhury', rollNumber: 'BCA-2025-033', email: 'diya.c@example.com', attendancePercentage: 90, statusToday: 'present' },
    ],
  },
  {
    id: 'cls-105',
    title: 'Computer Networks & Security',
    courseCode: 'BCA-302',
    courseName: 'Bachelor of Computer Applications',
    program: 'BCA',
    year: '3rd Year',
    semester: 'Semester 5',
    studentsCount: 26,
    room: 'Room 304',
    status: 'completed',
    iconType: 'mobile',
    mentorId: 'user-mentor',
    schedule: 'Mon, Thu · 01:30 PM - 03:00 PM',
    description: 'OSI and TCP/IP models, routing protocols, network socket programming, cryptography, and network security.',
    attendanceRate: 95,
    syllabusProgress: 100,
    enrolledStudents: [
      { id: 'st-13', name: 'Siddharth Iyer', rollNumber: 'BCA-2023-040', email: 'siddharth.i@example.com', attendancePercentage: 96, statusToday: 'present' },
    ],
  },
  {
    id: 'cls-106',
    title: 'Cloud Computing & DevOps',
    courseCode: 'BCA-306',
    courseName: 'Bachelor of Computer Applications',
    program: 'BCA',
    year: '3rd Year',
    semester: 'Semester 6',
    studentsCount: 24,
    room: 'Lab 2',
    status: 'completed',
    iconType: 'cloud',
    mentorId: 'user-mentor',
    schedule: 'Wed, Fri · 02:00 PM - 04:00 PM',
    description: 'Cloud architecture (AWS / Azure), Docker containerization, Kubernetes orchestration, and CI/CD automation pipelines.',
    attendanceRate: 90,
    syllabusProgress: 100,
    enrolledStudents: [
      { id: 'st-14', name: 'Meera Deshmukh', rollNumber: 'BCA-2023-048', email: 'meera.d@example.com', attendancePercentage: 92, statusToday: 'present' },
    ],
  },
]
